import type { ChannelRatingSeed } from './types';

/**
 * The Outreach Channel Matrix, as software.
 *
 * Twenty nine channels rated one to five for each of the two segments this
 * practice recruits. Generated from the practice's own workbook (Outreach
 * Channel Matrix, September 2026) so the ratings, the etiquette and the
 * evidence strength are the researched values rather than a paraphrase.
 *
 * These are SEED values. They are written into `channel_ratings` per tenant and
 * become tenant data the moment they land, because phase four writes source of
 * hire outcomes back into them so the matrix converges on this practice's own
 * results rather than published industry averages. See architecture.md s5.4.
 *
 * The etiquette field is not documentation. It is surfaced at the point of use,
 * and the policy engine blocks the channels whose own rules prohibit
 * unsolicited outreach. See architecture.md s9.4.
 */
export const CHANNEL_MATRIX_SEED: readonly ChannelRatingSeed[] = [
  {
    ordinal: 1,
    code: "linkedin_recruiter",
    name: "LinkedIn Recruiter (full seat)",
    category: "Direct-engagement platform",
    fitSeniorExecutive: 4,
    fitSeniorItConsultant: 5,
    roleInProcess: "Identify and contact",
    howExpertsUseIt: "Unrestricted search of 1B+ members with Boolean filters, Open to work and Active talent Spotlights, Talent Insights (RPS+), 150 InMail credits a month",
    etiquette: "Executives treat cold InMail as low-trust; keep messages under 400 characters and write each individually",
    evidenceStrength: "High",
    keySource: "LinkedIn Help a745199 and a414283; LinkedIn Talent Blog (Lewis, Apr 2021)",
  },
  {
    ordinal: 2,
    code: "linkedin_recruiter_lite",
    name: "LinkedIn Recruiter Lite",
    category: "Direct-engagement platform",
    fitSeniorExecutive: 2,
    fitSeniorItConsultant: 3,
    roleInProcess: "Identify and contact (entry level)",
    howExpertsUseIt: "Cheaper entry seat with basic search",
    etiquette: "Only 30 InMail credits a month and two Spotlights; no Open to work or Active talent filters",
    evidenceStrength: "High",
    keySource: "LinkedIn Help a745199 and a414283",
  },
  {
    ordinal: 3,
    code: "linkedin_sales_navigator",
    name: "LinkedIn Sales Navigator",
    category: "Direct-engagement platform",
    fitSeniorExecutive: 3,
    fitSeniorItConsultant: 2,
    roleInProcess: "Relationship mapping",
    howExpertsUseIt: "Account and lead filters for mapping who knows whom at target companies; useful for warm-introduction routing to executives",
    etiquette: "Not a hiring tool; filters barely overlap with Recruiter; smaller InMail budget",
    evidenceStrength: "Medium",
    keySource: "Warmy comparison (2026); Leonar (2025)",
  },
  {
    ordinal: 4,
    code: "linkedin_free_surfaces",
    name: "LinkedIn free surfaces (profile, posts, groups, events)",
    category: "Direct-engagement platform",
    fitSeniorExecutive: 3,
    fitSeniorItConsultant: 3,
    roleInProcess: "Presence and warm relationship",
    howExpertsUseIt: "A complete, credible recruiter profile plus consistent content and event hosting build the recognition that lifts reply rates; 27.0 million registered members in Canada",
    etiquette: "Groups and events are brand and relationship surfaces; little independent data on direct sourcing yield; commercial-use search limits apply to free accounts",
    evidenceStrength: "Medium",
    keySource: "DataReportal (Mar 2025); LinkedIn Future of Recruiting 2025",
  },
  {
    ordinal: 5,
    code: "x",
    name: "X (formerly Twitter)",
    category: "Social platform",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 3,
    roleInProcess: "Identify (niche technical and AI communities)",
    howExpertsUseIt: "Follow and engage with engineers who build in public; lists and hashtags to map a skill community's real influencers",
    etiquette: "Unaudited scale (estimates 368M to 586M monthly users); no response data; engage before any direct message",
    evidenceStrength: "Medium",
    keySource: "Paraform (2024); Dice Hiring; DemandSage and Statista",
  },
  {
    ordinal: 6,
    code: "bluesky_mastodon_threads",
    name: "Bluesky, Mastodon, Threads",
    category: "Social platform",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 2,
    roleInProcess: "Presence only",
    howExpertsUseIt: "Some technical-community presence; useful to follow what a target posts",
    etiquette: "Bluesky past its January 2025 peak (about 5.3M monthly users and falling); Mastodon under 1M monthly users; Threads is consumer-oriented",
    evidenceStrength: "Medium",
    keySource: "PLOS Absolutely Maybe (Oct 2025); Voxbooster (2026); Social Media Today (2025)",
  },
  {
    ordinal: 7,
    code: "github",
    name: "GitHub",
    category: "Developer platform",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 5,
    roleInProcess: "Identify and verify technical depth",
    howExpertsUseIt: "180M+ developers; contribution history, languages and libraries reveal real expertise; tools such as SeekOut score contributions; contact details sometimes in profile or README",
    etiquette: "Strong anti-cold-contact norms; profiles are sparse on location and employer; personalize around actual work or be ignored",
    evidenceStrength: "High (scale); Medium (etiquette)",
    keySource: "GitHub Octoverse 2025; SeekOut Help Center; daily.dev Recruiter",
  },
  {
    ordinal: 8,
    code: "stack_overflow",
    name: "Stack Overflow",
    category: "Developer platform",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 3,
    roleInProcess: "Verify expertise",
    howExpertsUseIt: "Reputation and answer history signal depth in a stack; the Developer Survey maps the audience",
    etiquette: "Jobs and Talent products were shut down on 1 April 2022; not an outreach engine",
    evidenceStrength: "High",
    keySource: "Stack Overflow shutdown notice (2022); Developer Survey 2024",
  },
  {
    ordinal: 9,
    code: "kaggle_and_hugging_face",
    name: "Kaggle and Hugging Face",
    category: "Developer platform",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 3,
    roleInProcess: "Identify (data and machine-learning talent)",
    howExpertsUseIt: "Competition rankings, notebooks, models and datasets identify proven data and AI builders",
    etiquette: "Vendor-guide evidence only; no hire-yield data; relevant only for data and AI roles",
    evidenceStrength: "Low",
    keySource: "Riem.ai (2026); HeroHunt.ai (2026)",
  },
  {
    ordinal: 10,
    code: "dev_to_hashnode_and",
    name: "Dev.to, Hashnode and personal blogs",
    category: "Developer platform",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 2,
    roleInProcess: "Identify and open warmly",
    howExpertsUseIt: "Find engineers who write about a stack; a specific comment on their writing is a credible opener",
    etiquette: "Branding and identification, not sourcing volume; no yield data",
    evidenceStrength: "Low",
    keySource: "HeroHunt.ai (2026); practitioner guidance",
  },
  {
    ordinal: 11,
    code: "slack_and_discord_communities",
    name: "Slack and Discord communities",
    category: "Community",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 3,
    roleInProcess: "Presence and warm relationship",
    howExpertsUseIt: "High-signal niche communities (DevOps, Kubernetes, data, security); participate, sponsor or host, and use the designated jobs channel",
    etiquette: "No-recruiter norms; unsolicited outreach outside the jobs channel gets you muted or banned",
    evidenceStrength: "Low to Medium",
    keySource: "daily.dev Recruiter guides (2026)",
  },
  {
    ordinal: 12,
    code: "reddit",
    name: "Reddit (r/ExperiencedDevs, r/devops, r/sysadmin, r/ITManagers)",
    category: "Community",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 2,
    roleInProcess: "Listen and learn",
    howExpertsUseIt: "Sentiment and vocabulary of senior technologists; what they value and complain about",
    etiquette: "Explicit rules against advertisements and surveys; cold pitching backfires",
    evidenceStrength: "High (rules)",
    keySource: "r/ExperiencedDevs rules; Hive Index (2026)",
  },
  {
    ordinal: 13,
    code: "aesc_bluesteps_and_retained",
    name: "AESC BlueSteps and retained-search network",
    category: "Executive network",
    fitSeniorExecutive: 4,
    fitSeniorItConsultant: 1,
    roleInProcess: "Identify and refer (executives)",
    howExpertsUseIt: "Discreet executive profiles visible to 16,000+ AESC consultants; 135K+ opportunity-ready executives",
    etiquette: "Built for retained firms; a staffing practice engages through relationships and referrals, not self-serve search",
    evidenceStrength: "High",
    keySource: "AESC, About BlueSteps (2026)",
  },
  {
    ordinal: 14,
    code: "gartner_c_level_communities",
    name: "Gartner C-level Communities (Evanta) and Gartner Peer Community",
    category: "Executive network",
    fitSeniorExecutive: 4,
    fitSeniorItConsultant: 1,
    roleInProcess: "Warm introduction (CIO, CISO)",
    howExpertsUseIt: "34 CIO communities serving 3,600+ CIOs; vetted, invitation-only; sponsor or participate to build relationships",
    etiquette: "Not a list to scrape; access is by membership or sponsorship",
    evidenceStrength: "High",
    keySource: "Evanta (2026); Gartner Connect with peers (2026)",
  },
  {
    ordinal: 15,
    code: "chief",
    name: "Chief (senior women leaders)",
    category: "Executive network",
    fitSeniorExecutive: 3,
    fitSeniorItConsultant: 1,
    roleInProcess: "Warm introduction",
    howExpertsUseIt: "Members from more than 10,000 organizations; a discovery surface for senior women leaders",
    etiquette: "Membership-gated; discovery and warm introduction only",
    evidenceStrength: "Medium to High",
    keySource: "Chief (2024)",
  },
  {
    ordinal: 16,
    code: "cio_association_of_canada",
    name: "CIO Association of Canada (CIOCAN)",
    category: "Executive network (Canada)",
    fitSeniorExecutive: 5,
    fitSeniorItConsultant: 2,
    roleInProcess: "Warm introduction (Canadian IT leaders)",
    howExpertsUseIt: "The premier community of CIOs, CISOs and IT leaders in Canada; CIO Peer Forum and the CIO.D designation with Rotman; chapters across the country",
    etiquette: "Membership-based; engage as a sponsor, speaker or member, not as a list source",
    evidenceStrength: "High",
    keySource: "CIOCAN (2026)",
  },
  {
    ordinal: 17,
    code: "technation",
    name: "TECHNATION (formerly ITAC)",
    category: "Industry association (Canada)",
    fitSeniorExecutive: 3,
    fitSeniorItConsultant: 2,
    roleInProcess: "Employer map and events",
    howExpertsUseIt: "National ICT association whose member roster maps Canadian technology employers; events convene their leaders",
    etiquette: "An industry body, not a candidate source",
    evidenceStrength: "High",
    keySource: "TECHNATION (2026)",
  },
  {
    ordinal: 18,
    code: "conferences_and_summits",
    name: "Conferences and summits (speaker and attendee lists)",
    category: "Offline and events",
    fitSeniorExecutive: 4,
    fitSeniorItConsultant: 4,
    roleInProcess: "Identify, meet and warm up",
    howExpertsUseIt: "Speaker and panelist lists double as talent maps; search researchers mine conference programmes; sponsor, host a dinner or roundtable, meet in person",
    etiquette: "Cost and time; do not pitch at the event, ask for a follow-up conversation",
    evidenceStrength: "Medium",
    keySource: "Cornerstone Search Group (2026); Tegze (Jul 2026)",
  },
  {
    ordinal: 19,
    code: "meetups_and_user_groups",
    name: "Meetups and user groups",
    category: "Offline and events",
    fitSeniorExecutive: 2,
    fitSeniorItConsultant: 4,
    roleInProcess: "Meet and warm up (technical talent)",
    howExpertsUseIt: "Cloud, DevOps, security and data user groups in Ottawa, Toronto, Montreal and Vancouver; sponsor pizza, host a venue, speak",
    etiquette: "Documented backlash against recruiters who attend to pitch; contribute first",
    evidenceStrength: "Low to Medium",
    keySource: "NextMantra (2026); daily.dev Recruiter (2026)",
  },
  {
    ordinal: 20,
    code: "professional_associations_and_chapters",
    name: "Professional associations and chapters (ISACA, ISC2, PMI, OWASP, CIPS)",
    category: "Offline and events",
    fitSeniorExecutive: 3,
    fitSeniorItConsultant: 4,
    roleInProcess: "Meet and warm up",
    howExpertsUseIt: "Chapter meetings and certification communities concentrate senior security, project and IT professionals; volunteer, sponsor or present",
    etiquette: "Member directories are not for cold outreach; build presence over months",
    evidenceStrength: "Medium",
    keySource: "Association sites; practitioner guidance",
  },
  {
    ordinal: 21,
    code: "alumni_networks",
    name: "Alumni networks (university, corporate, consulting-firm alumni)",
    category: "Network",
    fitSeniorExecutive: 4,
    fitSeniorItConsultant: 3,
    roleInProcess: "Identify and warm introduction",
    howExpertsUseIt: "Search researchers mine alumni networks when mapping a market; boomerang hires were 31% to 35% of new hires in 2025 and nearly two-thirds in the information sector",
    etiquette: "Requires a genuine shared affiliation or a connector; respect alumni-directory terms",
    evidenceStrength: "Medium to High",
    keySource: "Cornerstone Search Group (2026); ADP Research (May 2025)",
  },
  {
    ordinal: 22,
    code: "referrals_from_past_placements",
    name: "Referrals from past placements, clients and silver medalists",
    category: "Network",
    fitSeniorExecutive: 5,
    fitSeniorItConsultant: 5,
    roleInProcess: "Warm introduction and conversion",
    howExpertsUseIt: "Referrals convert at 11x inbound (Gem); about 40% of referred candidates reach interview (Ashby); top sourcers spend half their time on referrals (Adler)",
    etiquette: "Slow to build; make the ask effortless and give the connector an easy out",
    evidenceStrength: "High",
    keySource: "Gem 2026 Benchmarks; ElevateAI citing Ashby (2026); Adler (2015)",
  },
  {
    ordinal: 23,
    code: "speaking_circuits_podcasts_and",
    name: "Speaking circuits, podcasts and publishing",
    category: "Network",
    fitSeniorExecutive: 4,
    fitSeniorItConsultant: 3,
    roleInProcess: "Identify and open warmly",
    howExpertsUseIt: "Bylines, keynote listings and podcast appearances reveal who is visible and repositioning; an invitation to speak or contribute is a credible, flattering opener",
    etiquette: "Qualitative signal; no independent yield data; the invitation must be genuine",
    evidenceStrength: "Low to Medium",
    keySource: "AESC BlueSteps (2026); Korn Ferry (Mar 2025)",
  },
  {
    ordinal: 24,
    code: "regional_technology_hubs",
    name: "Regional technology hubs (Kanata North, Communitech, MaRS, Tech Weeks)",
    category: "Offline and events (Canada)",
    fitSeniorExecutive: 3,
    fitSeniorItConsultant: 4,
    roleInProcess: "Meet and warm up",
    howExpertsUseIt: "Kanata North represents 540+ companies in Canada's largest technology park; Communitech anchors Waterloo; Toronto and Waterloo Tech Weeks run dozens of events",
    etiquette: "Presence pays off over months; hubs are convenors, not candidate databases",
    evidenceStrength: "High (existence); Low (yield)",
    keySource: "Kanata North BA (2026); Communitech (2026); CityNews Kitchener (Sep 2025)",
  },
  {
    ordinal: 25,
    code: "certification_and_ambassador_communities",
    name: "Certification and ambassador communities (AWS Community Builders, Microsoft MVP, Google Developer Experts, CNCF Ambassadors)",
    category: "Community",
    fitSeniorExecutive: 1,
    fitSeniorItConsultant: 4,
    roleInProcess: "Identify (proven senior technologists)",
    howExpertsUseIt: "Published directories of vendor-recognized experts are pre-qualified shortlists of senior cloud and platform talent",
    etiquette: "Highly visible people who are approached often; lead with their work and a specific mandate",
    evidenceStrength: "Medium",
    keySource: "Program directories (see Canadian Directory sheet)",
  },
  {
    ordinal: 26,
    code: "email",
    name: "Email (personal or work)",
    category: "Messaging channel",
    fitSeniorExecutive: 5,
    fitSeniorItConsultant: 5,
    roleInProcess: "Make contact",
    howExpertsUseIt: "Top-preferred channel for job-opportunity communication across all age groups; 170 to 210 words, a reason-you line, five-touch sequence",
    etiquette: "Requires a verified address (raw exports run about 60% deliverable); personal email demands extra care",
    evidenceStrength: "High",
    keySource: "Bullhorn GRID 2023; Gem (Fall 2024); BounceZero (2026)",
  },
  {
    ordinal: 27,
    code: "linkedin_inmail_and_connection",
    name: "LinkedIn InMail and connection messages",
    category: "Messaging channel",
    fitSeniorExecutive: 3,
    fitSeniorItConsultant: 4,
    roleInProcess: "Make contact",
    howExpertsUseIt: "Under 400 characters performs 41% better than long; individually written +20%; Open to work members 75% more likely to respond; 65% of replies arrive within 24 hours",
    etiquette: "Executives see cold InMail as low-trust; prefer a warm introduction or a short confidential note",
    evidenceStrength: "High",
    keySource: "LinkedIn Talent Blog (Lewis, Apr 2021)",
  },
  {
    ordinal: 28,
    code: "phone_and_voicemail",
    name: "Phone and voicemail",
    category: "Messaging channel",
    fitSeniorExecutive: 4,
    fitSeniorItConsultant: 2,
    roleInProcess: "Advance the conversation",
    howExpertsUseIt: "Best for senior, confidential conversations once identified; referral-anchored opener; 20 to 40 second voicemail",
    etiquette: "Over-used relative to preference (22% of candidates report phone outreach); intrusive if cold; never disclose recruiting intent where it can be overheard",
    evidenceStrength: "Medium to High",
    keySource: "Bullhorn GRID 2023; Savage (Oct 2022); AESC Candidate Bill of Rights",
  },
  {
    ordinal: 29,
    code: "text_whatsapp_and_signal",
    name: "Text, WhatsApp and Signal",
    category: "Messaging channel",
    fitSeniorExecutive: 2,
    fitSeniorItConsultant: 2,
    roleInProcess: "Stay in touch once warm",
    howExpertsUseIt: "Fast and personal once a relationship exists; Boomers skew to text, younger groups to WhatsApp",
    etiquette: "Not for first contact; consent and privacy expectations are higher",
    evidenceStrength: "Medium",
    keySource: "Bullhorn GRID 2023",
  },
];
