import type { SignalTypeSeed } from './types';

/**
 * The twenty three openness signals, generated from the practice's own workbook
 * (Candidate Receptivity Scorecard, Signals Checklist tab, September 2026) so
 * the labels, categories, strengths and citations are the researched values.
 *
 * `subjectType` is the two clocks. A signal in the `employer_trigger` category
 * attaches to an ORGANIZATION and fans out to everyone tracked there; every
 * other signal attaches to a PERSON. That split is the highest leverage
 * mechanism in the system: one return to office mandate makes a whole floor
 * receptive, and it fires before any individual behaviour does. See
 * architecture.md s6.1.
 *
 * `points` follow the workbook's strength mapping: high 4, medium_high 3,
 * medium 2, low 1.
 *
 * `recencyWindowDays` is the one thing here that is NOT from the source. The
 * research gives a single 30 day window for the stacking rule and says only
 * that stale signals expire. These per signal lifetimes are practice defaults
 * set from what each signal actually is, they are tenant data, and they should
 * be tuned against the practice's own results. Where a source does speak to
 * duration, `windowNote` says so.
 */
export const SIGNAL_TYPE_SEED: readonly SignalTypeSeed[] = [
  {
    ordinal: 1,
    code: "recruiter_only_open_to",
    label: "Recruiter-only Open to Work setting is switched on",
    category: "linkedin_platform",
    subjectType: "person",
    strength: "high",
    points: 4,
    recencyWindowDays: 30,
    indicates: "Explicit, private openness to recruiter contact; LinkedIn reports these members are 75% more likely to respond",
    sourceCitation: "LinkedIn Help, Spotlights in Recruiter (2026); Greg Lewis, LinkedIn (Apr 2021)",
  },
  {
    ordinal: 2,
    code: "public_opentowork_photo_frame",
    label: "Public #OpenToWork photo frame",
    category: "linkedin_platform",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 30,
    indicates: "Active search; ambiguous for executives, who rarely use it because of perceived stigma",
    sourceCitation: "Greg Lewis, LinkedIn (Apr 2021); Goodspace (2026)",
  },
  {
    ordinal: 3,
    code: "burst_of_profile_updates",
    label: "Burst of profile updates (headline or summary rewrite, new skills, certifications)",
    category: "linkedin_behaviour",
    subjectType: "person",
    strength: "medium_high",
    points: 3,
    recencyWindowDays: 30,
    indicates: "Repositioning for a move; a single edit is routine grooming and does not count",
    sourceCitation: "LinkedIn Help, Active talent spotlight (2026); DataMagnet (Jul 2026)",
  },
  {
    ordinal: 4,
    code: "shared_or_updated_a",
    label: "Shared or updated a resume with recruiters",
    category: "linkedin_behaviour",
    subjectType: "person",
    strength: "high",
    points: 4,
    recencyWindowDays: 30,
    indicates: "Preparing to be found or to apply",
    sourceCitation: "LinkedIn Help, Active talent spotlight (2026)",
  },
  {
    ordinal: 5,
    code: "tenure_longer_than_average",
    label: "Tenure longer than average for the role at that company",
    category: "career_stage",
    subjectType: "person",
    strength: "high",
    points: 4,
    recencyWindowDays: 180,
    indicates: "LinkedIn flags these members as more likely to respond to outreach",
    sourceCitation: "LinkedIn Help, Active talent spotlight (2026)",
    windowNote: "A standing state rather than an event, so it persists.",
  },
  {
    ordinal: 6,
    code: "two_to_four_years",
    label: "Two to four years in role (shorter at start-ups; median tenure at Series A is 16 months)",
    category: "career_stage",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 180,
    indicates: "Restlessness and skill-readiness overlap; log as a watch flag, not an outreach trigger",
    sourceCitation: "DataMagnet (Jul 2026); Pin tenure study (2026)",
    windowNote: "A standing state rather than an event, so it persists.",
  },
  {
    ordinal: 7,
    code: "engaging_with_competitor_or",
    label: "Engaging with competitor or hiring content; following target companies",
    category: "linkedin_behaviour",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 30,
    indicates: "Window-shopping the market",
    sourceCitation: "LinkedIn Help, Interested in your company spotlight (2026)",
  },
  {
    ordinal: 8,
    code: "growing_network_accepting_recruiter",
    label: "Growing network; accepting recruiter connection requests",
    category: "linkedin_behaviour",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 30,
    indicates: "Quietly building exit bridges",
    sourceCitation: "DataMagnet (Jul 2026)",
  },
  {
    ordinal: 9,
    code: "employer_return_to_office",
    label: "Employer return-to-office mandate",
    category: "employer_trigger",
    subjectType: "organization",
    strength: "high",
    points: 4,
    recencyWindowDays: 90,
    indicates: "One in three executives given an RTO obligation say they will leave over it",
    sourceCitation: "Gartner press release (May 2024)",
  },
  {
    ordinal: 10,
    code: "layoffs_restructuring_or_hiring",
    label: "Layoffs, restructuring or hiring freeze at the employer",
    category: "employer_trigger",
    subjectType: "organization",
    strength: "high",
    points: 4,
    recencyWindowDays: 14,
    indicates: "Displaced and surviving talent both become receptive; act within days",
    sourceCitation: "DataMagnet citing Challenger, Gray & Christmas (2025); Korn Ferry (2026)",
    windowNote: "Relevance decays within days: outreach should land immediately after the announcement.",
  },
  {
    ordinal: 11,
    code: "merger_or_acquisition_involving",
    label: "Merger or acquisition involving the employer",
    category: "employer_trigger",
    subjectType: "organization",
    strength: "high",
    points: 4,
    recencyWindowDays: 180,
    indicates: "Integration uncertainty makes leaders receptive",
    sourceCitation: "Korn Ferry, 5 Lessons from M&A Leaders",
  },
  {
    ordinal: 12,
    code: "ceo_or_leadership_change",
    label: "CEO or leadership change (new boss)",
    category: "employer_trigger",
    subjectType: "organization",
    strength: "high",
    points: 4,
    recencyWindowDays: 180,
    indicates: "The layer below the departed leader becomes receptive; 2,221 CEOs left in 2024",
    sourceCitation: "Korn Ferry, The Great CEO Exodus Continues (Mar 2025)",
    windowNote: "The layer below a departed leader stays receptive for months.",
  },
  {
    ordinal: 13,
    code: "funding_round_down_round",
    label: "Funding round, down-round or IPO lock-up expiry",
    category: "employer_trigger",
    subjectType: "organization",
    strength: "medium",
    points: 2,
    recencyWindowDays: 90,
    indicates: "Hiring surge at the raiser, or instability that unsettles talent",
    sourceCitation: "Thrive TRM, candidate pipeline guide (2024)",
  },
  {
    ordinal: 14,
    code: "company_headcount_decline_over",
    label: "Company headcount decline over the past six months",
    category: "employer_trigger",
    subjectType: "organization",
    strength: "high",
    points: 4,
    recencyWindowDays: 90,
    indicates: "LinkedIn productises this as the High attrition spotlight",
    sourceCitation: "LinkedIn Help, RPS+ spotlights (2026)",
  },
  {
    ordinal: 15,
    code: "post_bonus_season",
    label: "Post-bonus season (Q1 to early Q2)",
    category: "compensation_cycle",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 90,
    indicates: "Retention cliff: resignations follow the payout",
    sourceCitation: "Search Solution Group; Celarity",
  },
  {
    ordinal: 16,
    code: "approaching_an_equity_vesting",
    label: "Approaching an equity vesting cliff or the end of a grant",
    category: "compensation_cycle",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 90,
    indicates: "Timeable window, especially for technology talent",
    sourceCitation: "techinterview.org, vesting schedules",
  },
  {
    ordinal: 17,
    code: "promoted_within_the_last",
    label: "Promoted within the last six months",
    category: "career_stage",
    subjectType: "person",
    strength: "medium_high",
    points: 3,
    recencyWindowDays: 180,
    indicates: "29% of first-time promotees left within a month versus 18% of peers; a new title raises marketability",
    sourceCitation: "ADP Research (Sep 2023); Korn Ferry (2023)",
    windowNote: "ADP puts the risk highest in the first one to six months after a first promotion.",
  },
  {
    ordinal: 18,
    code: "passed_over_for_promotion",
    label: "Passed over for promotion or title stagnation versus peers",
    category: "career_stage",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 180,
    indicates: "Cannot see what is next; a higher title is a top-four Canadian switching motivator (31%)",
    sourceCitation: "EC1 Partners (Aug 2026); Robert Half Canada (Jun 2024)",
  },
  {
    ordinal: 19,
    code: "contract_or_project_end",
    label: "Contract or project end date approaching",
    category: "career_stage",
    subjectType: "person",
    strength: "high",
    points: 4,
    recencyWindowDays: 90,
    indicates: "The highest-precision availability window for contractors and consultants",
    sourceCitation: "Thrive TRM, availability dimension (2024)",
  },
  {
    ordinal: 20,
    code: "relocation_commute_change_hq",
    label: "Relocation, commute change, HQ move or life event",
    category: "personal",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 90,
    indicates: "Situational openness",
    sourceCitation: "LinkedIn, Why and How People Change Jobs (2015)",
  },
  {
    ordinal: 21,
    code: "speaking_or_publishing_surge",
    label: "Speaking or publishing surge; first board or advisory role",
    category: "personal_brand",
    subjectType: "person",
    strength: "low",
    points: 1,
    recencyWindowDays: 90,
    indicates: "Possible repositioning ahead of a transition; corroborate before acting",
    sourceCitation: "Korn Ferry, The Great CEO Exodus Continues (Mar 2025)",
  },
  {
    ordinal: 22,
    code: "high_crm_engagement_score",
    label: "High CRM engagement score (email opens, clicks, job views)",
    category: "engagement_data",
    subjectType: "person",
    strength: "high",
    points: 4,
    recencyWindowDays: 30,
    indicates: "Bullhorn: a score over 75 generally means actively engaged and interested",
    sourceCitation: "Bullhorn Knowledge Base, Understanding Bullhorn Scores",
  },
  {
    ordinal: 23,
    code: "silver_medalist_or_prior",
    label: "Silver medalist or prior finalist in an earlier search",
    category: "relationship",
    subjectType: "person",
    strength: "medium",
    points: 2,
    recencyWindowDays: 365,
    indicates: "Pre-qualified and warm; fast to re-engage",
    sourceCitation: "Thrive TRM, candidate pipeline guide (2024)",
    windowNote: "A relationship, not an event. It stays warm for a year.",
  },
];
